### ISSUE TITLE
You're Better Than Me

### ISSUE THREAD

**Issue by nitrodragon** [EthanBar/JavaFx-Calculator#1]
Okay, I thought I was the superior coder here, but, looking through your code here, that's clearly not the case. Lol guess I'm the weak link of this team. :P

**Comment by EthanBar** [comment]
Nah, I've just been going full no-life this past week. After all I've got a whole class to work on this. Still going to need your help when we get to Arrays and actual code logic, which I'm willing to bet you're a step up on

**Comment by nitrodragon** [comment]
That wasn't a tutorial? Dang. If I didn't have freaking Online French, I'd be pulling a no-lifer myself over spring break. Also, the Calculator loses precision at a certain point (freaking Java doubles and BigDecimals).

**Comment by EthanBar** [comment]
I'll be stuck in remote Arizona in 90 degree weather with most likely zero internets 😢

**Comment by nitrodragon** [comment]
Who needs internets when you've got IntelliJ Premium? Also, that means I'll be able to do Threads and Network handling and get ahead of you.

**Comment by EthanBar** [comment]
I don't even know where to start on those 🤔

**Comment by nitrodragon** [comment]
Me neither. They're a little (a lot) beyond my skillset at the moment.

**Comment by nitrodragon** [comment]
`private int[] column = {0,0,1,2,0,1,2,0,1,2,0,1,2};`
`private int[] row = {4,3,3,3,2,2,2,1,1,1,0,0,0};`

Was a bit confused on these

**Comment by EthanBar** [comment]
Most confusing part of this for sure. I used a for loop to setup the buttons for numbers 0-9.
```Java
Button[] nums = new Button[10];
for (int i = 0; i < nums.length; i++){
     nums[i] = new Button();
     grid.add(nums[i], column[i], row[i]);
```
Those variables correspond to the grid position of each button. So button 1 (which is really 0, cuz arrays) is at grid positon (4,0). Then button 2 is at (3,0) an so forth.

**Comment by nitrodragon** [comment]
Wow. Mega-hecka smart. That makes a ton of sense. I'm gonna mass-download documentation and try to read it on the ride. The 50-page Array documentation is still on my computer in Quick's room. 😳😂😭 I'll grab it after school—don't think I'm going to track today. Should I print it?
